import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  backgroundOrbPrimary: {
    backgroundColor: '#0b3a42',
    borderRadius: 220,
    height: 220,
    opacity: 0.38,
    position: 'absolute',
    right: -80,
    top: -30,
    width: 220,
  },
  backgroundOrbSecondary: {
    backgroundColor: '#7a2e2e',
    borderRadius: 260,
    bottom: 80,
    height: 260,
    left: -140,
    opacity: 0.18,
    position: 'absolute',
    width: 260,
  },
  content: {
    gap: 18,
    padding: 20,
    paddingBottom: 36,
  },
  heroCard: {
    backgroundColor: '#111c2e',
    borderColor: '#26354f',
    borderRadius: 28,
    borderWidth: 1,
    gap: 16,
    padding: 22,
  },
  heroHeader: {
    flexDirection: 'row',
    gap: 16,
    justifyContent: 'space-between',
  },
  heroCopy: {
    flex: 1,
    gap: 8,
  },
  kicker: {
    color: '#8dd6c9',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.8,
    textTransform: 'uppercase',
  },
  title: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '800',
    lineHeight: 34,
  },
  subtitle: {
    color: '#bcc8dc',
    fontSize: 15,
    lineHeight: 22,
  },
  signOutButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#1d2a40',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  signOutText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  roleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roleChip: {
    backgroundColor: '#15233a',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  roleChipText: {
    color: '#d7ddeb',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  demoBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#4b3b1f',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  demoBadgeText: {
    color: '#f4cc8b',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  tabRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tabButton: {
    backgroundColor: '#15233a',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  tabButtonActive: {
    backgroundColor: '#f0b35c',
  },
  tabButtonText: {
    color: '#d7ddeb',
    fontSize: 13,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#0b1220',
  },
  banner: {
    backgroundColor: '#19324f',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bannerCompact: {
    marginTop: 14,
  },
  bannerError: {
    backgroundColor: '#4b2128',
  },
  bannerSuccess: {
    backgroundColor: '#1d4b37',
  },
  bannerText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 20,
  },
  loadingCard: {
    alignItems: 'center',
    backgroundColor: '#111c2e',
    borderColor: '#26354f',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    padding: 28,
  },
  loadingLabel: {
    color: '#d7ddeb',
    fontSize: 15,
    fontWeight: '600',
  },
  panel: {
    backgroundColor: '#111c2e',
    borderColor: '#26354f',
    borderRadius: 24,
    borderWidth: 1,
    gap: 16,
    padding: 20,
  },
  panelHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  panelTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '800',
  },
  searchInput: {
    backgroundColor: '#17253a',
    borderColor: '#2a3b58',
    borderRadius: 16,
    borderWidth: 1,
    color: '#ffffff',
    fontSize: 15,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  eventRail: {
    gap: 12,
    paddingRight: 4,
  },
  eventCard: {
    backgroundColor: '#17253a',
    borderColor: '#2a3b58',
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    minHeight: 164,
    padding: 18,
    width: 240,
  },
  eventCardSelected: {
    backgroundColor: '#20314a',
    borderColor: '#f0b35c',
  },
  eventStatus: {
    color: '#8dd6c9',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
  },
  eventCardTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  eventCardMeta: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
  },
  inlineLoader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  inlineLoaderText: {
    color: '#bcc8dc',
    fontSize: 14,
  },
  eventDetailHeader: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  eventDetailCopy: {
    flex: 1,
    gap: 6,
  },
  eventDetailMeta: {
    color: '#bcc8dc',
    fontSize: 14,
    lineHeight: 20,
  },
  capacityBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#173643',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  capacityBadgeLabel: {
    color: '#8dd6c9',
    fontSize: 12,
    fontWeight: '800',
  },
  eventDescription: {
    color: '#d7ddeb',
    fontSize: 14,
    lineHeight: 21,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  stack: {
    gap: 12,
  },
  sellableCard: {
    backgroundColor: '#17253a',
    borderRadius: 18,
    gap: 14,
    padding: 16,
  },
  sellableTopRow: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sellableCopy: {
    flex: 1,
    gap: 4,
  },
  sellableTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
  },
  sellableDescription: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#2c2942',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  categoryBadgeText: {
    color: '#e9d7ff',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sellableMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  sellablePrice: {
    color: '#f4cc8b',
    fontSize: 14,
    fontWeight: '800',
  },
  sellableAvailability: {
    color: '#8dd6c9',
    fontSize: 13,
    fontWeight: '700',
  },
  sellableInCart: {
    color: '#d7ddeb',
    fontSize: 13,
    fontWeight: '700',
  },
  sellableActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  quantityControl: {
    alignItems: 'center',
    backgroundColor: '#111c2e',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  quantityButton: {
    alignItems: 'center',
    backgroundColor: '#22314c',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  quantityButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  quantityValue: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
    minWidth: 20,
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#f0b35c',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#0b1220',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#20314a',
    borderRadius: 16,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  checkoutRow: {
    flexDirection: 'row',
    gap: 12,
  },
  checkoutSummary: {
    backgroundColor: '#17253a',
    borderRadius: 18,
    gap: 10,
    padding: 16,
  },
  checkoutAmountCard: {
    backgroundColor: '#20314a',
    borderColor: '#2f4a70',
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  checkoutAmountLabel: {
    color: '#bcc8dc',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  checkoutAmountValue: {
    color: '#f4cc8b',
    fontSize: 32,
    fontWeight: '900',
    lineHeight: 36,
  },
  checkoutMethodRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  checkoutMethodChip: {
    backgroundColor: '#16253a',
    borderColor: '#2a3f60',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  checkoutMethodChipActive: {
    backgroundColor: '#f0b35c',
    borderColor: '#f0b35c',
  },
  checkoutMethodChipText: {
    color: '#d7ddeb',
    fontSize: 12,
    fontWeight: '700',
  },
  checkoutMethodChipTextActive: {
    color: '#0b1220',
  },
  checkoutHelperText: {
    color: '#9eb1cd',
    fontSize: 12,
    lineHeight: 18,
  },
  cartItemCard: {
    alignItems: 'center',
    backgroundColor: '#17253a',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 16,
  },
  cartItemCopy: {
    flex: 1,
    gap: 4,
  },
  cartItemTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  cartItemMeta: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
  },
  cartFooter: {
    backgroundColor: '#17253a',
    borderRadius: 18,
    gap: 10,
    padding: 16,
  },
  clearText: {
    color: '#8dd6c9',
    fontSize: 14,
    fontWeight: '700',
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    color: '#bcc8dc',
    fontSize: 13,
  },
  summaryValue: {
    color: '#ffffff',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  summaryValueEmphasis: {
    color: '#f4cc8b',
    fontSize: 15,
  },
  ticketCard: {
    backgroundColor: '#111c2e',
    borderColor: '#26354f',
    borderRadius: 24,
    borderWidth: 1,
    gap: 16,
    padding: 20,
  },
  ticketHeader: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  ticketEventTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
  },
  ticketEventMeta: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
  },
  ticketStatusChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#173643',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  ticketStatusUsed: {
    backgroundColor: '#4b2128',
  },
  ticketStatusText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  ticketBody: {
    flexDirection: 'row',
    gap: 16,
  },
  ticketMetaStack: {
    flex: 1,
    gap: 10,
    justifyContent: 'center',
  },
  payloadBox: {
    backgroundColor: '#17253a',
    borderRadius: 18,
    gap: 8,
    padding: 14,
  },
  payloadLabel: {
    color: '#8dd6c9',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  payloadText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 18,
  },
  passMatrix: {
    backgroundColor: '#f6f3ea',
    borderRadius: 16,
    gap: 2,
    padding: 12,
  },
  passMatrixRow: {
    flexDirection: 'row',
    gap: 2,
  },
  passMatrixCell: {
    backgroundColor: '#f6f3ea',
    borderRadius: 1,
    height: 6,
    width: 6,
  },
  passMatrixOn: {
    backgroundColor: '#111111',
  },
  scannerEventRow: {
    gap: 10,
    paddingRight: 4,
  },
  scannerEventChip: {
    backgroundColor: '#17253a',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  scannerEventChipActive: {
    backgroundColor: '#f0b35c',
  },
  scannerEventText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  cameraCard: {
    backgroundColor: '#17253a',
    borderRadius: 20,
    gap: 12,
    overflow: 'hidden',
    padding: 12,
  },
  cameraViewport: {
    borderRadius: 18,
    height: 260,
    overflow: 'hidden',
    position: 'relative',
  },
  cameraView: {
    flex: 1,
  },
  cameraOverlay: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  cameraTarget: {
    borderColor: '#f0b35c',
    borderRadius: 24,
    borderWidth: 2,
    height: 160,
    width: '72%',
  },
  cameraHint: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
  },
  cameraFallback: {
    alignItems: 'center',
    backgroundColor: '#17253a',
    borderRadius: 20,
    gap: 10,
    padding: 20,
  },
  cameraFallbackTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  cameraFallbackText: {
    color: '#bcc8dc',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#17253a',
    borderRadius: 20,
    gap: 8,
    padding: 22,
  },
  emptyStateTitle: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '800',
  },
  emptyStateDescription: {
    color: '#bcc8dc',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
});
